<?php

return array(
    //Leadtype: Home Security
    //https://tl.leadportal.com/new_api/index.php?action=detail&TYPE=27&func=genericPostlead
    '27' => array(
        'post_param' => array(
            'TYPE',
            'Test_Lead',
            'Skip_XSL',
            'Match_With_Partner_ID',
            'Redirect_URL',
            's1',
            's2',
            's3',
            's4',
            's5',
            'User_Agent',
            'SRC',
            'Landing_Page',
            'IP_Address',
            'Sub_ID',
            'Pub_ID',
            'Optout',
            'Unique_Identifier',
            '___pageid___',
            'universal_leadid',
            'xxTrustedFormCertUrl',
            'TCPA_Consent',
            'TCPA_Language',
            'First_Name',
            'Last_Name',
            'Address',
            'City',
            'State',
            'Zip',
            'Primary_Phone',
            'Secondary_Phone',
            'County',
            'Email',
            'property_ownership',
            'HasSystem',
            'CurrentSecuritySystemCompany',
        ),
        'default_value' => array(
            'SRC'		=> 'WebForm_test',
        ),
        'excludes_param' => array(
            'Redirect_URL'              => 1,
            'Match_With_Partner_ID'     => 1,
            'Test_Lead'                 => 1,
            'Skip_XSL'                  => 1,
        ),
    ),

    //https://tl.leadportal.com/new_api/index.php?action=detail&TYPE=25&func=genericPostlead
    //Leadtype: Windows
    '25' => array(
        'post_param' => array(
            'TYPE',
            'Test_Lead',
            'Skip_XSL',
            'Match_With_Partner_ID',
            'Redirect_URL',
            's1',
            's2',
            's3',
            's4',
            's5',
            'User_Agent',
            'SRC',
            'Landing_Page',
            'IP_Address',
            'Sub_ID',
            'Pub_ID',
            'Optout',
            'Unique_Identifier',
            '___pageid___',
            'universal_leadid',
            'xxTrustedFormCertUrl',
            'TCPA_Consent',
            'TCPA_Language',
            'First_Name',
            'Last_Name',
            'Address',
            'City',
            'State',
            'Zip',
            'Primary_Phone',
            'Secondary_Phone',
            'County',
            'Email',
            'property_ownership',
            'ProjectType',
            'NumberOfWindows',
        ),
        'default_value' => array(
            'SRC'		=> 'WebForm_test',
        ),
        'excludes_param' => array(
            'Redirect_URL'              => 1,
            'Match_With_Partner_ID'     => 1,
            'Test_Lead'                 => 1,
            'Skip_XSL'                  => 1,
        ),
    ),

    //https://tl.leadportal.com/new_api/index.php?action=detail&TYPE=23&func=genericPostlead
    //Leadtype: Roofing
    '23' => array(
        'post_param' => array(
            'TYPE',
            'Test_Lead',
            'Skip_XSL',
            'Match_With_Partner_ID',
            'Redirect_URL',
            's1',
            's2',
            's3',
            's4',
            's5',
            'User_Agent',
            'SRC',
            'Landing_Page',
            'IP_Address',
            'Sub_ID',
            'Pub_ID',
            'Optout',
            'Unique_Identifier',
            '___pageid___',
            'universal_leadid',
            'xxTrustedFormCertUrl',
            'TCPA_Consent',
            'TCPA_Language',
            'First_Name',
            'Last_Name',
            'Address',
            'City',
            'State',
            'Zip',
            'Primary_Phone',
            'Secondary_Phone',
            'County',
            'Email',
            'property_ownership',
            'ProjectType',
            'RoofType',
        ),
        'default_value' => array(
            'SRC'		=> 'WebForm_test',
        ),
        'excludes_param' => array(
            'Redirect_URL'              => 1,
            'Match_With_Partner_ID'     => 1,
            'Test_Lead'                 => 1,
            'Skip_XSL'                  => 1,
        ),
    ),

    //https://tl.leadportal.com/new_api/index.php?action=detail&TYPE=21&func=genericPostlead
    //Leadtype: Mortgage
    '21' => array(
        'post_param' => array(
            'TYPE',
            'Test_Lead',
            'Skip_XSL',
            'Match_With_Partner_ID',
            'Redirect_URL',
            'IP_Address',
            'SRC',
            'Landing_Page',
            'Sub_ID',
            'Pub_ID',
            'Optout',
            'Unique_Identifier',
            'User_Agent',
            'xxTrustedFormCertUrl',
            's1',
            's2',
            's3',
            's4',
            's5',
            's6',
            'SecureRights_Token',
            'TCPA_Consent',
            'TCPA_Language',
            'LeadiD_Token',
            'First_Name',
            'Last_Name',
            'Address',
            'City',
            'State',
            'Zip',
            'Email',
            'Primary_Phone',
            'Secondary_Phone',
            'Military_Or_Veteran',
            'Credit_Status',
            'Loan_Type',
            'Property_Type',
            'Loan_Value',
            'Home_Value',
            'First_Mortgage_Balance',
            'First_Mortgage_Rate',
            'Second_Mortgage',
            'Second_Mortgage_Balance',
            'Second_Mortgage_Rate',
            'Found_Home',
            'LTV',
        ),
        'default_value' => array(
            'SRC'		=> 'WebForm_test',
        ),
        'excludes_param' => array(
            'Redirect_URL'              => 1,
            'Match_With_Partner_ID'     => 1,
            'Test_Lead'                 => 1,
            'Skip_XSL'                  => 1,
        ),
    ),
);